### PR TITLE
Improve the DIS report queueing and status code reporting on webhook calls

### PR DESCRIPTION
**Pull request by craigpratt**
Changed DisClient.send to clear the staged events based on returned status

Also added a max_staged parameter to the constructor. When the
 max is reached add_attack_event will fail.

Also changed the webhook handler to return 200 even if the DisClient.send()
 fails - since it's now improved to do the Right Things.

Also parameterizing the DisClient queue length.

### CODE REVIEW

**Comment by craigpratt** [comment]
@sjcjonker please have a look and let me know what you think!

**Comment by bjyurkovich** [comment]
@craigpratt I'm more curious than anything - is this a DX/UX feature need from the client API/connector standpoint, or is adding this a bandaid to help stave off another problem inn the system?

There are things with the backend than can be done to help this if you added this for performance (memory, speed) reasons...

**Comment by sjcjonker** [comment]
Hi Craig, in my view this should be OK to go in. I do believe if we exceed max staged events it's acceptable to loose them.

**Comment by craigpratt** [comment]
@bjyurkovich This is really all about ensuring the queue only contains events that have a reasonable expectation of being upload-able. 

So if the server returns a 4xx error on a report upload, it should not be queued as this is the server saying "your data is bad". Keeping it in the queue will just sam it up and ensure that no reports are uploaded (this is what we were seeing with the size exceeded error).. If the server returns a 5xx error, than the report can be queued as the server is saying "I'm having an issue with your data - but it may resolve." So I think these should be queued.

I'm a bit on the fence about whether the queueing even makes sense when there's an error. It might make more sense for the queue to just get cleared when there's any error except perhaps a connection error. But I'll have to sleep on that a bit... ;^J

**Comment by bjyurkovich** [comment]
@craigpratt Makes sense, probably good to handle the case regardless.

Did the increasing the max size in nginx config help at all?  How big are the typical payloads?  Might consider breaking them down into multiple calls (since they are all based on the same `eventId`) if the payloads get too big...I would have to check, but marking the same `eventId` across multiple calls is probably OK.

**Comment by craigpratt** [comment]
Sorry @bjyurkovich - I fell into a week-long training hole last week.

Yeah, it seems the nginx max upload setting resolved the primary upload issue @sjcjonker was seeing. So the queuing isn't as critical at the moment. But I do think queuing would be good to have for cases where (a) there's a connectivity loss between the client and server, and (b) cases where we want/need to take down the server for a (hopefully brief) period. 

I'm hoping we're not talking about enough reports to consume excess memory. If so we'd probably want to look at storing the queued reports on-disk.

**Comment by craigpratt** [comment]
OK - I did an update to this branch to expose the queue length setting to the docker management script.

I'm considering it "ready to merge".

**Pull request merged**
